version: "3.8"
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: todo_password
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
  
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["--default-authentication-plugin=mysql_native_password"]

  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data: